GET http://localhost:3004/products


###


POST http://localhost:3004/products
Content-Type: application/json

{
    "productName": "Ski",
    "brand": "Nike",
    "price": 295
}


###

DELETE http://localhost:3004/products/5e583debbee7fc4cac175f5f